name: test-Linux-arm64ðŸ“¦

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ linux-workflow, build-all ]
  workflow_dispatch:


jobs:
  build-n-publish:
    name: BuildðŸ“¦ for Linux
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
        architecture: [ 'arm64' ]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            mesa-common-dev 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade setuptools 
          python -m pip install wheel
      
      - name: Build a source tarball
        if: ${{ matrix.python-version == '3.13'}}
        run: python setup.py sdist

      - name: Build a binary wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload artifacts for download
        uses: actions/upload-artifact@v4
        with:
          name: dist-python-${{ matrix.python-version }}-${{ matrix.architecture }}
          path: |
            dist/*.whl
            dist/*.tar.gz
          retention-days: 5
